on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Analisa Imagen y Crea Contenedor'
        default: 'Running Build And Analize Docker Image'
        type: string        
name: AnalizeImageDocker
run-name: ${{inputs.run-name}}
jobs:
  ImageSecurity:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Docker
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_SECRETS_USER }}
            password: ${{ secrets.DOCKER_SECRETS_PASS }}
  
        - name: Construcción Docker
          run: |
            docker build --tag flowter/tarea3_v2:latest .
  
        - name: Análisis de Seguridad de la Imágen
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'flowter/tarea3_v2:latest'
            format: 'table'
            exit-code: 0       
