on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Analisa Imagen y Crea Contenedor'
        default: 'Running Build And Analize Docker Image'
        type: string        
name: AnalizeImageCreateDocker
run-name: ${{inputs.run-name}}
jobs:
  Docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Docker
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_SECRETS_USER }}
            password: ${{ secrets.DOCKER_SECRETS_PASS }}
  
        - name: Construcci칩n Docker
          run: |
            docker build --tag flowter-netflix/tarea3_v2:latest .
  
        - name: An치lisis de Seguridad de la Im치gen
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'flowter-netflix/tarea3_v2:latest'
            format: 'table'
        
        - name: Subir Im치gen Docker
          run: |
            docker push flowter-netflix/tarea3_v2
  Deploy:
           needs: Docker
           runs-on: self-hosted
      
           steps:
      
           - name: Pull Image Docker
             run: |
               docker pull flowter-netflix/tarea3_v2:latest
         
           - name: Liberacion
             run: |
               docker run -p 8081:80 --name flowter-netflix -d flowter-netflix/tarea3_v2:latest
