run-name: Workflow An치lisis 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  SAST:
    uses: ./.github/workflows/SAST.yml
    with:
      run-name: "An치lisis de C칩digo"
  SCA:
    needs: SAST
    uses: ./.github/workflows/SCA.yml
    with:
      run-name: "An치lisis de Vulnerabilidades"
