run-name: Workflow Análisis 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  SAST:
    uses: ./.github/workflows/SAST.yml
    with:
      run-name: "Análisis de Código"
    secrets: inherit  
  SCA:
    needs: SAST
    uses: ./.github/workflows/SCA.yml
    with:
      run-name: "Análisis de Vulnerabilidades"
    secrets: inherit
  AnalizeImage:
    needs: SCA
    uses: ./.github/workflows/AnalisaImagen.yml
    with:
      run-name: "Análisis de Seguridad de Imágen"
    secrets: inherit
  PushDeployDocker:
    needs: AnalizeImage
    uses: ./.github/workflows/SubirImagen.yml
    with:
      run-name: "Crea y Sube Contenedor"
    secrets: inherit
  zap_scan:
    needs: AnalizeImage
    uses: ./.github/workflows/zap_scan.yml
    with:
      run-name: "OWASP SAP"
    secrets: inherit
