run-name: Workflow An치lisis 
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  SAST:
    uses: Flowter/Tarea2_V2/.github/workflows/SAST.yml@main
    with:
      run-name: "An치lisis de C칩digo"
  SCA:
    needs: SAST
    uses: Flowter/Tarea2_V2/.github/workflows/SCA.yml@main
    with:
      run-name: "An치lisis de Vulnerabilidades"
