run-name: Flujo de Análisis 

on:
  push:
  workflow_dispatch:
     
jobs:
    Analisis_Estatico:
      runs-on: ubuntu-latest
      steps:
        
        - name: Clonación Repositorio
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: SAST
          uses: ./.github/workflows/SAST.yml
          with:
            run-name: "Análisis de Código"
            secrets: inherit
        
        - name: SCA   
          uses: ./.github/workflows/SCA.yml
          with:
            run-name: "Análisis de Vulnerabilidades"
            secrets: inherit
    
    #AnalisisDeImagen:
    
      
#    secrets: inherit
#  SAST:
#    uses: ./.github/workflows/SAST.yml
#    with:
#      run-name: "Análisis de Código"
#    secrets: inherit  
#  SCA:
#    needs: SAST
#    uses: ./.github/workflows/SCA.yml
#    with:
#      run-name: "Análisis de Vulnerabilidades"
#    secrets: inherit
#  AnalizeImageCreateDocker:
#    needs: SCA
#    uses: ./.github/workflows/AnalisaImagen.yml
#    with:
#      run-name: "Análisis de Seguridad de Imágen y Creación de Contenedor"
#    secrets: inherit
  #PushDeployDocker:
    #needs: AnalizeImage
    #uses: ./.github/workflows/SubirImagen.yml
    #with:
      #run-name: "Crea y Sube Contenedor"
    #secrets: inherit
  #zap_scan:
   # needs: AnalizeImageCreateDocker
    #uses: ./.github/workflows/zap_scan.yml
    #secrets: inherit
