on:
  workflow_call:
name: SCA  
jobs:

  DependencyCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: SCA
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'TAREA3_V2'
          path: '.'
          format: 'HTML'
          
      - name: Reporte SCA
        uses: actions/upload-artifact@master
        with:
           name: Dependency report
           path: ${{github.workspace}}/reports
