on:
  workflow_call:

    inputs:
      run-name:
        required: false
        description: 'Despliegue del Contenedor'
        default: 'Push/Deploy Docker'
        type: string        
name: DeployDocker
run-name: ${{inputs.run-name}}

jobs:
  
  ConstruirDocker:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        
        - name: Docker
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_SECRETS_USER }}
            password: ${{ secrets.DOCKER_SECRETS_PASS }}
  
        - name: Construcción Docker
          run: |
            docker build --tag flowter/tarea3_v2:latest .
  
        - name: Subir Imágen Docker
          run: |
            docker push flowter/tarea3_v2 
  
  DesplegarDocker:
           needs: ConstruirDocker
           runs-on: self-hosted
      
           steps:
      
           - name: Pull Image Docker
             run: |
               docker pull flowter/tarea3_v2:latest
         
           - name: Liberacion
             run: |
               docker run -p 8081:80 --name flowter-netflix -d flowter/tarea3_v2:latest
           
           - name: Sleep
             run: |
               sleep 30
