on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'OWASP ZAP SCAN'
        default: 'zap_scan'
        type: string        
name: zap_scan
run-name: zap_scan

jobs:
  
  zap_scan:
  
    runs-on: self-hosted
    steps:
      
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:8081/'
          
